version: '3.8'

services:
  # Backend 
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    env_file:
      - ./backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    container_name: email_classifier_backend

  # Frontend 
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    container_name: email_classifier_frontend