[project]
name = "backend"
version = "0.1.0"
description = "Backend do app emailClassifier"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "python-multipart>=0.0.20",
    "uvicorn[standard]>=0.35.0",
]
