services:
  - type: web
    name: email-classifier
    env: docker
    repo: https://github.com/Gs-Toledo/EmailClassifier
    rootDir: backend
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: GOOGLE_API_KEY
        sync: false

  - type: static
    name: email-classifier-frontend
    env: static
    repo: https://github.com/Gs-Toledo/EmailClassifier
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: classificador-backend